"""initial migration

Revision ID: 18d0d2499266
Revises: 
Create Date: 2018-01-28 12:05:19.582686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d0d2499266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageseval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagename', sa.String(length=255), nullable=False),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('poor', sa.Integer(), nullable=True),
    sa.Column('eval', sa.Text(), nullable=True),
    sa.Column('eval_time', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['imagesinfodf.index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_imagesinfodf_index', table_name='imagesinfodf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_imagesinfodf_index', 'imagesinfodf', ['index'], unique=False)
    op.drop_table('imageseval')
    # ### end Alembic commands ###
